# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Jest MHA

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: NPM build, test
        run: |
          npm ci
          npm test
