# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Jest MHA

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: NPM build, test
        run: |
          npm ci
          npm test
